### ISSUE TITLE
error waiting for postgres when starting graphql-engine

### ISSUE THREAD

**Issue by donnerc** [shopozor/backend#72]
removing `restart: always` from `docker-compose.yaml` file causes the `graphql-engine` to fail on start because `postgres` is not ready to accept connections when `graphql-engine` makes its first attempt. The bug is reported here https://github.com/hasura/graphql-engine/issues/1168 and the solution proposed is to put `restart` to `always`.

In order for the container not to start at OS boot time, just make a `docker-compose down` when development work is finished.

We should therefore restore `restart: always` in `docker-compose.yaml`

**Comment by zadigus** [comment]
Interesting. I experienced exactly that issue on our ci environment.

**Comment by zadigus** [comment]
I am against the idea to set `restart: always` in `docker-compose.yaml` because I think this is precisely what was fixed by https://github.com/hasura/graphql-engine/issues/1168. I am also against the idea to do that in the `docker-compose-tests.yaml`, because this will for sure pollute my local development docker infrastructure with automatically restarted docker containers, which is annoying. 

I think that for local use we can just wait until the engine is ready. That is also easy to fix on our CI / CD environment which I am currently fixing.

**Comment by zadigus** [comment]
As explained in https://github.com/hasura/graphql-engine/issues/1168, in the hasura cli-migration image, they use this code to wait until the port is available (cf. [hasura sources](https://github.com/hasura/graphql-engine/blob/master/scripts/cli-migrations/docker-entrypoint.sh#L25)):
```
# wait for a port to be ready
wait_for_port() {
    local PORT=$1
    log "waiting $HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT for $PORT to be ready"
    for i in `seq 1 $HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT`;
    do
        nc -z localhost $PORT > /dev/null 2>&1 && log "port $PORT is ready" && return
        sleep 1
    done
    log "failed waiting for $PORT" && exit 1
}
```
